# 1. Web Server Port
server.port=8080

# 2. Database Connection Credentials
spring.datasource.url=jdbc:mysql://localhost:3306/secureiot_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
# REPLACE THE TEXT BELOW WITH THE EXACT PASSWORD YOU MADE DURING INSTALLATION!
spring.datasource.password=admin2026

# 3. Hibernate (The Database Mapper) Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect